version: '3.1'

services:
  proxy:
    image: traefik
    networks: [api]
    command: --web --docker --docker.swarmmode
    networks:
      - api
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager
  auth:
    image: codemeister/homebrew-monitor-auth:0.1.3
    networks: [api]
    environment:
      SERVICE_PORT: 8080
      SERVICE_ROUTE: /auth
    deploy:
      labels:
        traefik.port: 8080
        traefik.frontend.rule: PathPrefix:/auth
  rest:
    image: codemeister/homebrew-monitor-rest:0.1.0
    networks: [api]
    environment:
      SERVICE_PORT: 8080
      SERVICE_ROUTE: /rest
      AUTH_PORT: 80
    deploy:
      labels:
        traefik.port: 8080
        traefik.frontend.rule: PathPrefix:/rest

networks:
  api: